name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test_and_check_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: rustup component add rustfmt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ci-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ci-${{ runner.os }}-cargo-

      - name: Format check
        run: |
          cargo fmt --all -- --check

      - name: Test
        run: cargo test

      - name: Run main
        run: cargo run
